# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11.3
    working_directory: /go/src/github.com/{{.Repo.Owner.Login}}/{{.Repo.Name}}
    steps:
      - checkout
      - setup_remote_docker
      - run: docker build -t {{.Repo.Owner.Login}}/{{.Repo.Name}}:`git rev-parse HEAD` .
      - run: docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
      - run: docker push {{.Repo.Owner.Login}}/{{.Repo.Name}}:`git rev-parse HEAD`
  latest:
    docker:
      - image: circleci/golang:1.11.3
    working_directory: /go/src/github.com/{{.Repo.Owner.Login}}/{{.Repo.Name}}
    steps:
      - checkout
      - setup_remote_docker
      - run: docker build -t {{.Repo.Owner.Login}}/{{.Repo.Name}}:latest .
      - run: docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
      - run: docker push {{.Repo.Owner.Login}}/{{.Repo.Name}}:latest

workflows:
  version: 2
  build:
    jobs:
      - build:
          context: docker push
      - latest:
          context: docker push
          filters:
            branches:
              only: master
